load("//:localize.bzl", "localize")

localize(
    name = "localize_test",
    srcs = [
        "en.lproj/Localizable.strings",
        "es.lproj/Localizable.strings",
    ],
    visibility = [
        "//Example/Source:__pkg__",
    ],
)
